version: '3.3'
services:
    discordldap:
        env_file:
            - ./.env
        ports:
            - '80:80'
        image: fedeit/discordldap
        volumes:
            - ./db:/usr/src/app/db
